= _Coffee Maker_ Essential Security Requirements
:showtitle:
:icons: font
:revnumber: 0.1
:revdate: 2019-06-13

:iTC-longname: Coffee Maker
:iTC-shortname: CM-iTC


== Status
The CCDB Working Group has been requested to develop an Essential Security Requirements (ESR) that captures the fundamental requirements for {iTC-longname}. This initial draft contains material that was provided by the requestor, the <Requesting Country>, for a cPP.
[NOTE]
====
This document uses the Network Devices ESR as a template. Several examples are left in some sections to show what types of information needs to be defined.
====

== Background and Purpose
This document describes the high-level fundamental security requirements expected of any {iTC-longname}. It is intended to provide a minimal, baseline set of requirements which can be built upon by future cPPs to provide an overall set of security solutions for <whatever the product does>.

[NOTE]
====
At this point you will need to provide enough background and purpose of the devices that will be evaluated to the cPP to make it clear what the scope of the iTC will be.
====

== Use Case(s)
[NOTE]
====
This should provide examples of the types of use cases solved by an evaluated device.

This can encompass different expected uses of the devices, or different form factors (such as an integrated component of a larger device or where the evaluated product is separate). 

There may be only a single use case for a base-PP where PP-Modules may actually represent specific cases (an example would be Network Devices has only one use case but each PP-Module would cover some variation of the use case).
====

== Resources to be Protected
[NOTE]
====
This section provides a list of the type of resources that will be protected when a product is evaluated. Some examples are below.
====

* Any management interfaces, any critical data (e.g., audit data).
* Authentication data/credentials.
* Updates to the product.

== Attacker access
[NOITE]
====
How can the attacker gain access to the product? 
====

* An attacker can send arbitrary packets to network interfaces of the device
* An attacker can present false authentication credentials to access the device

== Attacker Resources
[NOTE]
====
Generally the attacker will have "an arbitrary amount of time to study ..." whatever the thing the device is protecting against. For example for a Network Device, the ability to study traffic to/from the device, for biometrics it could be to study how it works and time to make fakes to test.
====

* An arbitrary amount of time to study input/output from a device
* Many sample devices to test and attack

== Boundary of Device
[NOTE]
====
In most cases the boundary is probably the entire device, but if it is intended as a subcomponent, then it may be more restrictive. 

If the boundary is more complex, a diagram may be useful here.

The two examples below are the commonly accepted boundary definitions.
====

* The hardware, firmware and software of the device define the physical boundary.
* All of the security functionality is contained and executed within the physical boundary of the device.

== Essential Security Requirements
[NOTE]
====
This is the most critical section, the bullet list of requirements the cPP shall have to meet. 

This should be a focused list to product better results.

The list below is taken from the Network Device ESR.
====

* The remote administration functions shall use cryptography to protect this communication path.
* The device shall be capable of auditing administrative actions, including any configuration changes and rebooting of the device.
* The device shall provide an authentication mechanism for local and remote administrators, as well as the device itself (e.g., the device maintains an authentication credential that can be used to authenticate it to an administrator’s client).
* The device shall provide a cryptographic means to validate the source of updates to be installed on the device.
* The device shall require any default passwords / other credentials to be changed.
* The device shall protect keys, key material, and authentication credentials from unauthorized disclosure.
* The device is robust against malformed network packets, including denial-of-service attacks.
* The device shall provide self-tests to ensure the security functions it implements are operating correctly.

== Assumptions
[NOTE]
====
These will form the basis of the assumptions in the cPP.
====

* Administrators (if existing) are trustworthy and well trained
* The device is protected from physical attacks by the wider environment

== Optional Extensions
[NOTE]
====
These are like "stretch" goals. Things that may not be available in all products but which are available (and likely desirable).
====

Requirements captured in this section may already be realized in some products in this technology class, but this ESR is not mandating these capabilities exist in “baseline” level products.

* The device shall be able to assign which interface(s) remote administration may take place

== Objective Requirements
[NOTE]
====
These are "future" goals. No products may meet these yet but they are called out as important to the iTC as defined in the founding documents. 

This section may not be in all ESRs.
====

Requirements specified here specify security-relevant behaviour that is not expected to be realized currently in products, but capabilities that may be mandated in future versions of the ESR and resulting cPPs.

* The device shall have internal security features to make the device more resilient to security breaches.
* The device shall provide two-factor authentication natively on the device (i.e., does not rely on a separate device to provide this capability).

== Outside the Scope of Evaluation
[NOTE]
====
Things listed here can be explicitly excluded from consideration for requirements. For example types of attacks that may not be readily able to be handled or are just considered out of scope (such as for USB where a device is compromised and returned to the user). 

Things listed here may end up being used in ESRs for PP-Modules based on a base-PP later. For example, additional functionality of the device (such as a VPN gateway on top of a network device) may be excluded here.
====

* Additional security functionality that a security-enabled network device may employ (e.g., firewall, virtual private networking) is outside the scope, as these will be specified in other ESRs.
* Virus scanning, including email scanning.
* Intrusion detection/prevention capabilities
* Network Address Translation (NAT) as a security function..
* Virtualized network functions.
