= Security Problem Definition for SaaS
:showtitle:
:toc: macro
:imagesdir: images
:icons: font
:revnumber: 0.1
:revdate: 2019-09-06

:iTC-longname: Common Criteria in the Cloud iTC
:iTC-shortname: CCitC-iTC
:iTC-email: cm-itc-mailing-list@gmail.com
:iTC-website: https://cc-in-the-cloud.github.io/
:iTC-GitHub: https://github.com/cc-in-the-cloud/admin/

:sectnums!:

== Revision History

.Revision history
[%header,cols="1,2,4"]
|===
|Version 
|Date 
|Description

|0.1
|<DATE>
|Initial Release for iTC Review

|
|
|


|===

toc::[]
:sectnums:

== Compliant Targets of Evaluation

Software applications to be considered for evaluation under this PP can be categorized under the following broad categories:

. IT Products deployed in a SaaS environment 
. Operating Systems, Database Management Systems, Authentication Servers, etc that are implemented in PaaS solutions.
. General Purpose Compute Platforms, Baseboard Management Controllers, Hardware Security Modules, Trusted Platform Modules, etc that are implemented in IaaS solutions.

In addition to the above categories there are large number of products that are not explicitly outlined above, which may also be suitable for compliant TOEs. While such applications could be evaluated under the Software Application cPP, it is not the intention of this iTC to specifically address this category. The iTC doesn’t believe the consumer grade app ecosystem would support the cost and timelines associated with a typical Common Criteria evaluation.

One more way (and perhaps a more useful way in the context of creating SFRs) to categorize apps is based on type of installation/deployment. The following categories are in scope of the first iteration of the module:

* Traditional software running on an execution environment, e.g: Enterprise agent applications/sensors
* Software appliance type of applications. E.g.:
* Enterprise management application
* Distributed applications (e.g. enterprise resource planning systems)

The following categories are out of scope of the module:

* Smart Cards
* Hard Copy Devices

Products that are inherently centered around physical instantiations are not applicable to SaaS implementations.

== Security Problem Definition
[GUIDANCE]
====
At this stage, specific CC language is not required, the threats, assumptions and security policies can be written in "plain" language.

Each one should get a title, like T.LOCAL_ATTACK or A.PROPER_ADMIN

If there is nothing to be placed into a specific category, then it should be stated: There are no XXX for Coffee Makers.
====

=== Threats

T.CONFIGURATION::

T.CREDENTIAL:: For SaaS use cases, an application may access data stores or credentials that would not be provided by the host Operating System. 

T.DATA_SOVEREIGNTY::

T.INSIDER_THREAT:: An attacker from the Cloud Service Provider has vastly increased attacker potential versus an external threat actor. To be explored by the Trusted Provider Subgroup.

[note]
CSP admin access to encryption keys may be countered in FEDRAMP and we can map SFRs to his example.
SaaS applications may implement their own encryption layer to protect from insider threat at the cloud storage object level.

Zero trust / MFA SFRs may be appropriate here

T.MULTI_TENANT::


=== Assumptions
A.PROPER_ADMIN:: The administrator of the application is trusted to administer the software within compliance of the applied enterprise security policy.

 
=== Organizational Security Policies
There are no OSPs for coffee makers.


== Security Objectives 

=== Security Objectives for the TOE
O.INTEGRITY:: The TOE will provide a means to verify the integrity and authenticity of downloaded updates.

=== Security Objectives for the Operational Environment
OE.PROPER_ADMIN:: The administrator of the application software is trusted to administer the software within compliance of the applied enterprise security policy.